const desktop = [
  // #region แนะนำหน้าหลัก
  {
    index: 1,
    tutorialBarPosition: "bottom",
    tutorialContent: `สวัสดี! ฉันชื่อ <span>วินนี่</span> จะมาแนะนำการใช้งานใน <span>หน้าหลัก</span> นี้ให้ทุกคนเอง`,
    textAlign: "start",
    isButtonNext: true,
    isButtonBack: false,
    imageBackground: "box-tutorial.webp",
    isBackground: true,
    imageCharacterIdle: "/images/box_main/box-tutorial-professor-winny-1.webp",
    imageCharacterAction: "/images/box_main/box-tutorial-professor-winny-2.webp",
    positionCharacter: "right",
    animationCharacterFadeIn:"animate__fadeInUp",
    animationCharacterFadeOut:"animate__fadeOutDown",
    isButtonSkip: true,
    positionButtonSkip: "right",
    infomationContentList: [],
    isAction: true,
    isActive: false,
    delay: "1000",
    delayMobile: "0",
    isButtonFinish: false,
    showContentType: "",
    skipTo: "level-mode",
  },
  {
    index: 2,
    tutorialBarPosition: "bottom",
    tutorialContent: `เริ่มกันที่ มุมซ้ายบน คือ <span>หน้าโปรไฟล์</span> สามารถแก้ไขข้อมูลส่วนตัว<br/> และตรวจสอบคะแนน, ความก้าวหน้าในการเรียน <br/>
    หรือใบประกาศความสำเร็จต่าง ๆ ได้เลย`,
    textAlign: "start",
    isButtonNext: true,
    isButtonBack: true,
    imageBackground: "box-tutorial.webp",
    isBackground: true,
    imageCharacterIdle: "/images/box_main/box-tutorial-professor-winny-1.webp",
    positionCharacter: "right",
    animationCharacterFadeIn:"animate__fadeInUp",
    animationCharacterFadeOut:"",
    isButtonSkip: true,
    positionButtonSkip: "right",
    infomationContentList: [
      {
        isShowContent: true,
        content: "ส่วนโปรไฟล์ เลเวลตัวละครและชื่อเล่น",
        position: "top: 19%; left: 2.75%;",
        isShowHand: true,
        handImage: "/images/icon_main/icon-tutorial-hand.webp",
        handPosition: "top: 10%; left: 24.5%;transform: rotate(90deg);",
      },
    ],
    isAction: false,
    isActive: false,
    delay: "0",
    delayMobile: "0",
    isButtonFinish: false,
    showContentType: "show-profile",
    skipTo: "level-mode",
  },
  {
    index: 3,
    tutorialBarPosition: "bottom",
    tutorialContent: `เมื่อเข้า หน้าโปรไฟล์ และกดที่ สถิติแบบฝึกหัด<br>
    หากมี <span>ความก้าวหน้าเฉลี่ยถึง 80%</span> ก็จะสามารถดาวน์โหลด <span>ใบประกาศ</span> ได้เลย! <br/>
    สู้ๆ นะ!`,
    textAlign: "start",
    isButtonNext: true,
    isButtonBack: true,
    imageBackground: "box-tutorial.webp",
    isBackground: true,
    imageCharacterIdle: "/images/box_main/box-tutorial-professor-winny-3.webp",
    positionCharacter: "right",
    animationCharacterFadeIn:"",
    animationCharacterFadeOut:"",
    isButtonSkip: true,
    positionButtonSkip: "right",
    infomationContentList: [
      {
        isShowContent: true,
        content: "สถิติแบบฝึกหัดของตัวละคร",
        position: "top: 1.7%; left:43.8%;",
        isShowHand: true,
        handImage: "/images/icon_main/icon-tutorial-hand.webp",
        handPosition: "top:6.8%; left:37.5%;transform: rotate(-10deg);",
      },
      {
        isShowContent: true,
        content: "ห้องใบประกาศ",
        position: "top: 18%; left:75.7%;",
        isShowHand: true,
        handImage: "/images/icon_main/icon-tutorial-hand.webp",
        handPosition: "top:24%; left: 70%;transform: rotate(-7deg);",
      },
    ],
    isAction: true,
    isActive: true,
    delay: "0",
    isButtonFinish: false,
    showContentType: "show-profile-detail",
    skipTo: "level-mode",
  },
  {
    index: 4,
    tutorialBarPosition: "bottom",
    tutorialContent: `ถัดมาที่ มุมขวาบน คือ ปุ่มจัดการต่างๆ ได้แก่ <span>กล่องจดหมาย</span>, <span>ตั้งค่า</span> และ <br/> <span>ออกจากระบบ</span>`,
    textAlign: "start",
    isButtonNext: true,
    isButtonBack: true,
    imageBackground: "box-tutorial.webp",
    isBackground: true,
    imageCharacterIdle: "/images/box_main/box-tutorial-professor-winny-1.webp",
    positionCharacter: "right",
    animationCharacterFadeIn:"",
    animationCharacterFadeOut:"",
    isButtonSkip: true,
    positionButtonSkip: "left",
    infomationContentList: [
      {
        isShowContent: true,
        content: "กล่องจดหมาย และ ข่าวสาร",
        position: "top: 2%; left:50%;",
        isShowHand: true,
        handImage: "/images/icon_main/icon-tutorial-hand.webp",
        handPosition: "top:2%; left: 79%;transform: rotateY(180deg) rotate(40deg);",
      },
      {
        isShowContent: true,
        content: "ตั้งค่าการเล่น",
        position: "top: 13.7%; left:67%;",
        isShowHand: true,
        handImage: "/images/icon_main/icon-tutorial-hand.webp",
        handPosition: "top:11%; left: 85.3%;transform: rotateY(180deg) rotate(75deg);",
      },
      {
        isShowContent: true,
        content: "ออกจากระบบ",
        position: "top: 25.3%; left:79%;",
        isShowHand: true,
        handImage: "/images/icon_main/icon-tutorial-hand.webp",
        handPosition: "top:13.5%; left: 93.3%;transform: rotateY(0deg) rotate(133deg);",
      },
    ],
    isAction: true,
    isActive: true,
    delay: "0",
    isButtonFinish: false,
    showContentType: "button-header",
    skipTo: "level-mode",
  },
  {
    index: 5,
    tutorialBarPosition: "bottom",
    tutorialContent: `ต่อกันที่ มุมซ้ายล่าง คือ <span>เมนู</span> ที่รวบรวม
<br/> ความสนุก และการจัดการ ตัวละครของทุกคน
<br/> ลอง <span>กดเปิด</span> ดูสิ!`,
    textAlign: "start",
    isButtonNext: false,
    isButtonBack: true,
    imageBackground: "box-tutorial-overlay-left.webp",
    isBackground: true,
    imageCharacterIdle: "/images/box_main/box-tutorial-professor-winny-1.webp",
    positionCharacter: "right",
    animationCharacterFadeIn:"",
    animationCharacterFadeOut:"",
    isButtonSkip: true,
    positionButtonSkip: "right",
    infomationContentList: [
      {
        isShowContent: false,
        content: "ส่วนโปรไฟล์ เลเวลตัวละครและชื่อเล่น",
        position: "top: 18.3%; left: 2.75%;",
        isShowHand: true,
        handImage: "/images/icon_main/icon-tutorial-hand.webp",
        handPosition: "top:73%; left: 8.5%;transform: rotate(-13deg);",
        isAnimtionHand: true,
      },
    ],
    isAction: true,
    isActive: false,
    delay: "0",
    isButtonFinish: false,
    showContentType: "menu",
    skipTo: "level-mode",
  },
  {
    index: 6,
    tutorialBarPosition: "bottom",
    tutorialContent: `ภายในจะประกอบไปด้วย <br/>
    <span>เมนูต่าง ๆ</span> มากมาย <br/>
    ไว้ลองเข้าไปเล่นกันดูนะ!`,
    textAlign: "start",
    isButtonNext: true,
    isButtonBack: true,
    imageBackground: "box-tutorial-overlay-left.webp",
    isBackground: true,
    imageCharacterIdle: "/images/box_main/box-tutorial-professor-winny-3.webp",
    positionCharacter: "right",
    animationCharacterFadeIn:"",
    animationCharacterFadeOut:"",
    isButtonSkip: true,
    positionButtonSkip: "right",
    infomationContentList: [
      {
        isShowContent: true,
        content: "ลำดับคะแนน",
        position: "top:20.5%; left: 2.785%;",
        isShowHand: true,
        handImage: "/images/icon_main/icon-tutorial-hand.webp",
        handPosition: "top:31.5%; left:4.5%;transform: rotateY(180deg) rotate(-30deg);",
      },
      {
        isShowContent: true,
        content: "หน้าเก็บอุปกรณ์แต่งตัวละคร",
        position: "top: 20.5%; left: 29.7%;",
        isShowHand: true,
        handImage: "/images/icon_main/icon-tutorial-hand.webp",
        handPosition: "top:26.5%; left: 24%;transform: rotate(-20deg);",
      },
      {
        isShowContent: true,
        content: "ร้านค้า",
        position: "top: 44.5%; left: 44.3%;",
        isShowHand: true,
        handImage: "/images/icon_main/icon-tutorial-hand.webp",
        handPosition: "top:42%; left: 38%;transform: rotate(45deg);",
      },
      {
        isShowContent: true,
        content: "กล่องสุ่มปริศนา",
        position: "top: 66%; left:23%;",
        isShowHand: true,
        handImage: "/images/icon_main/icon-tutorial-hand.webp",
        handPosition: "top:59.3%; left: 18.6%;transform: rotate(65deg);",
      },
    ],
    isAction: true,
    isActive: false,
    delay: "0",
    isButtonFinish: false,
    showContentType: "show-menu",
    skipTo: "level-mode",
  },
  {
    index: 7,
    tutorialBarPosition: "bottom",
    tutorialContent: `ปิดท้ายกันที่ มุมขวาล่าง คือ <br/>
พื้นที่การเรียนรู้ และ<span>กิจกรรมต่าง ๆ</span> <br/>
เข้าสู่ <span>บทเรียน</span> สุดสนุก ได้ที่นี่!`,
    textAlign: "start",
    isButtonNext: true,
    isButtonBack: true,
    imageBackground: "box-tutorial-overlay-right.webp",
    isBackground: true,
    imageCharacterIdle: "/images/box_main/box-tutorial-professor-winny-3.webp",
    positionCharacter: "left",
    animationCharacterFadeIn:"",
    animationCharacterFadeOut:"",
    isButtonSkip: true,
    positionButtonSkip: "left",
    infomationContentList: [
      {
        isShowContent: true,
        content: "กิจกรรมพิเศษ",
        position: "top: 69%; left:47%;",
        isShowHand: true,
        handImage: "/images/icon_main/icon-tutorial-hand.webp",
        handPosition: "top:73%; left: 65.5%;transform: rotateY(180deg) rotate(-10deg);",
      },
      {
        isShowContent: true,
        content: "กิจกรรมทบทวนความรู้",
        position: "top: 56.5%; left:56.5%;",
        isShowHand: true,
        handImage: "/images/icon_main/icon-tutorial-hand.webp",
        handPosition: "top:68.9%; left: 77.5%;transform: rotateY(180deg) rotate(-50deg);",
      },
      {
        isShowContent: true,
        content: "เริ่มเรียน",
        position: "top: 50.7%; left:83.3%;",
        isShowHand: true,
        handImage: "/images/icon_main/icon-tutorial-hand.webp",
        handPosition: "top:61.8%; left: 88.5%;transform: rotateY(180deg) rotate(-75deg);",
      },
    ],
    isAction: true,
    isActive: true,
    delay: "0",
    isButtonFinish: false,
    showContentType: "show-button-learn",
    skipTo: "level-mode",
  },
  // #endregion

  // #region ระบบเลเวล
  {
    index: 8,
    tutorialBarPosition: "bottom",
    tutorialContent: `นี่คือ <span>ระบบเลเวล</span> ตัวเลขที่อยู่บน <span>ตราประดับ</span> เรียกว่า <span>เลเวล</span> <br/>
    ซึ่งตราประดับจะเปลี่ยนแปลงไปตามเลเวลที่เพิ่มขึ้นของคุณ! <br/>
    เมื่อ<span>เข้าเรียนและทำแบบฝึกหัด</span> คุณก็จะได้รับ <span>ค่า XP</span> เพื่อให้เลเวลอัพ!"`,
    textAlign: "start",
    isButtonNext: true,
    isButtonBack: false,
    imageBackground: "box-tutorial.webp",
    isBackground: true,
    imageCharacterIdle: "/images/box_main/box-tutorial-professor-winny-1.webp",
    positionCharacter: "right",
    animationCharacterFadeIn:"animate__fadeInUp",
    animationCharacterFadeOut:"",
    isButtonSkip: false,
    positionButtonSkip: "left",
    infomationContentList: [
      {
        isShowContent: true,
        content: "เลเวลและตราประดับ",
        position: "top: 20.88%; left:8.7231%;",
        isShowHand: true,
        handImage: "/images/icon_main/icon-tutorial-hand.webp",
        handPosition: "top:12.7%; left: 4.9%;transform: rotate(75deg);",
      },
    ],
    isAction: true,
    isActive: true,
    delay: "0",
    isButtonFinish: false,
    showContentType: "show-level",
    skipTo: "",
  },
  {
    index: 9,
    tutorialBarPosition: "bottom",
    tutorialContent: `รู้หรือไม่? ทุกครั้งที่คุณ <span>เลเวลอัพ</span> คุณจะได้รับของ <span>รางวัลสุดพิเศษ!</span> <br/> ลองมาดูกันเลยว่าคุณจะได้อะไรบ้างเมื่อเลเวลอัพ!`,
    textAlign: "start",
    isButtonNext: true,
    isButtonBack: true,
    imageBackground: "box-tutorial.webp",
    isBackground: true,
    imageCharacterIdle: "/images/box_main/box-tutorial-professor-winny-3.webp",
    positionCharacter: "right",

    animationCharacterFadeIn:"",
    animationCharacterFadeOut:"",
    isButtonSkip: false,
    positionButtonSkip: "left",
    infomationContentList: [
      {
        isShowContent: true,
        content: "รับรางวัลเมื่อเลเวลอัพ",
        position: "top: 12.85%; left:32.3%;",
        isShowHand: true,
        handImage: "/images/icon_main/icon-tutorial-hand.webp",
        handPosition: "top:12.2%; left: 25.7%;transform: rotate(30deg);",
      },
    ],
    isAction: true,
    isActive: true,
    delay: "0",
    isButtonFinish: false,
    showContentType: "show-profile-level-reward",
    skipTo: "",
  },
  {
    index: 10,
    tutorialBarPosition: "bottom",
    tutorialContent: ``,
    isButtonNext: false,
    isButtonBack: false,
    imageBackground: "box-tutorial.webp",
    isBackground: false,
    imageCharacterIdle: "/images/box_main/box-tutorial-professor-winny-1.webp",
    positionCharacter: "right",

    animationCharacterFadeIn:"",
    animationCharacterFadeOut:"",
    isButtonSkip: false,
    positionButtonSkip: "left",
    infomationContentList: [],
    isAction: true,
    isActive: true,
    delay: "0",
    isButtonFinish: false,
    showContentType: "show-level-up",
    skipTo: "",
  },
  {
    index: 11,
    tutorialBarPosition: "bottom",
    tutorialContent: `เลเวลอัพแล้ว <span>กดรับรางวัล (Claim Reward)</span> ดูสิ`,
    textAlign: "center",
    isButtonNext: false,
    isButtonBack: false,
    imageBackground: "box-tutorial.webp",
    isBackground: true,
    imageCharacterIdle: "/images/box_main/box-tutorial-professor-winny-3.webp",
    positionCharacter: "right",

    animationCharacterFadeIn:"",
    animationCharacterFadeOut:"",
    isButtonSkip: false,
    positionButtonSkip: "left",
    infomationContentList: [
      {
        isShowContent: false,
        content: "",
        position: "top: 0%; left:0%;",
        isShowHand: true,
        handImage: "/images/icon_main/icon-tutorial-hand.webp",
        handPosition: "top:64%; left: 56%;transform: rotate(55deg);",
        isAnimtionHand: true,
      },
    ],
    isAction: true,
    isActive: true,
    delay: "0",
    isButtonFinish: false,
    showContentType: "show-claim-reward",
    skipTo: "",
  },
  {
    index: 12,
    tutorialBarPosition: "bottom",
    tutorialContent: `กด <span>รับทั้งหมด (Claim All)</span> เพื่อรับรางวัลทั้งหมดได้เลย!`,
    textAlign: "center",
    isButtonNext: false,
    isButtonBack: false,
    imageBackground: "box-tutorial.webp",
    isBackground: true,
    imageCharacterIdle: "/images/box_main/box-tutorial-professor-winny-1.webp",
    positionCharacter: "right",

    animationCharacterFadeIn:"",
    animationCharacterFadeOut:"",
    isButtonSkip: false,
    positionButtonSkip: "left",
    infomationContentList: [
      {
        isShowContent: false,
        content: "",
        position: "top: 0%; left:0%;",
        isShowHand: true,
        handImage: "/images/icon_main/icon-tutorial-hand.webp",
        handPosition: "top:77%; left: 56.5%;transform: rotate(55deg);",
        isAnimtionHand: true,
      },
    ],
    isAction: true,
    isActive: true,
    delay: "0",
    isButtonFinish: false,
    showContentType: "show-level-reward",
    skipTo: "",
  },
  {
    index: 13,
    tutorialBarPosition: "bottom",
    tutorialContent: ``,
    isButtonNext: false,
    isButtonBack: false,
    imageBackground: "box-tutorial.webp",
    isBackground: false,
    imageCharacterIdle: "/images/box_main/box-tutorial-professor-winny-3.webp",
    positionCharacter: "right",

    animationCharacterFadeIn:"",
    animationCharacterFadeOut:"",
    isButtonSkip: false,
    positionButtonSkip: "left",
    infomationContentList: [],
    isAction: true,
    isActive: true,
    delay: "0",
    isButtonFinish: false,
    showContentType: "show-get-reward",
    skipTo: "",
  },
  // #endregion

  // #region โหมดการเรียนเป็นคู่
  {
    index: 14,
    tutorialBarPosition: "bottom",
    tutorialContent: `นอกจากนี้ การเข้าสู่ <span>โหมดการเรียนเป็นคู่ (Buddy Mode)</span> <br/>
ให้นักเรียนกรอก <span>รหัสผู้ใช้งาน และรหัสผ่าน</span> ของเพื่อนที่ต้องการจับคู่ <br/> จากนั้นกดปุ่ม <span>เริ่มจับคู่ (Pair)</span>`,
    textAlign: "start",
    isButtonNext: true,
    isButtonBack: false,
    imageBackground: "box-tutorial.webp",
    isBackground: true,
    imageCharacterIdle: "/images/box_main/box-tutorial-professor-winny-1.webp",
    positionCharacter: "right",

    animationCharacterFadeIn:"",
    animationCharacterFadeOut:"",
    isButtonSkip: true,
    positionButtonSkip: "right",
    infomationContentList: [
      {
        isShowContent: true,
        content: "โหมดการเรียนเป็นคู่",
        position: "top: 31.1111%; left:10.0356%;",
        isShowHand: true,
        handImage: "/images/icon_main/icon-tutorial-hand.webp",
        handPosition: "top:44%; left: 16.425%;transform: rotateY(180deg) rotate(-15deg);",
      },
      {
        isShowContent: true,
        content: "เริ่มจับคู่",
        position: "top: 52.7777%; left:63.8481%;",
        isShowHand: true,
        handImage: "/images/icon_main/icon-tutorial-hand.webp",
        handPosition: "top:53.5%; left: 56.8%;transform: rotate(15deg);",
      },
    ],
    isAction: true,
    isActive: true,
    delay: "0",
    isButtonFinish: false,
    showContentType: "show-buddy-mode",
    skipTo: "finish-mode",
  },
  {
    index: 15,
    tutorialBarPosition: "bottom",
    tutorialContent: `และเมื่อต้องการ <span>ออกจากโหมดการเรียนเป็นคู่</span> ให้กด <span>เลิกจับคู่ (Unpair)</span><br/> เพื่อออกจากการจับคู่`,
    textAlign: "start",
    isButtonNext: true,
    isButtonBack: true,
    imageBackground: "box-tutorial.webp",
    isBackground: true,
    imageCharacterIdle: "/images/box_main/box-tutorial-professor-winny-1.webp",
    positionCharacter: "right",

    animationCharacterFadeIn:"",
    animationCharacterFadeOut:"",
    isButtonSkip: true,
    positionButtonSkip: "right",
    infomationContentList: [
      {
        isShowContent: true,
        content: "ออกจากโหมดจับคู่",
        position: "top: 60%; left:50.9%;",
        isShowHand: true,
        handImage: "/images/icon_main/icon-tutorial-hand.webp",
        handPosition: "top:61.5%; left: 44%;transform: rotate(15deg);",
      },
    ],
    isAction: true,
    isActive: true,
    delay: "0",
    isButtonFinish: false,
    showContentType: "show-unpair-buddy-mode",
    skipTo: "finish-mode",
  },
  // #endregion

  // #region จบการสอน
  {
    index: 16,
    tutorialBarPosition: "bottom",
    tutorialContent: `พร้อมสำหรับการเรียนกันแล้ว! <br/>
ถ้าสงสัยตรงไหน <span>กดปุ่ม</span> <span
            style="
              padding: clamp(1.875px, 0.1875vw, 3px) clamp(6.25px, 0.625vw, 10px);
              border: clamp(1.875px, 0.1875vw, 3px) solid #f7b90d;
              border-radius: 50%;
              font-size: clamp(12px, 1.2vw, 20px);
              color:#f7b90d;
            "
            class="fas fa-info"
          ></span> <span>เพื่อดูคำแนะนำอีกครั้งได้นะ</span> <br/>
ขอให้สนุกในการเรียนไปกับ Winner English`,
    textAlign: "start",
    isButtonNext: true,
    isButtonBack: false,
    imageBackground: "box-tutorial.webp",
    isBackground: true,
    imageCharacterIdle: "/images/box_main/box-tutorial-professor-winny-3.webp",
    imageCharacterAction: "/images/box_main/box-tutorial-professor-winny-2.webp",
    positionCharacter: "right",
    animationCharacterFadeIn:"",
    animationCharacterFadeOut:"animate__fadeOutDown",
    isButtonSkip: false,
    positionButtonSkip: "right",
    infomationContentList: [
      {
        isShowContent: true,
        content: "แนะนำการใช้งาน",
        position: "top: 6.7%; left:37.5%;",
        isShowHand: true,
        handImage: "/images/icon_main/icon-tutorial-hand.webp",
        handPosition: "top:3%; left: 31.4%;transform: rotate(40deg);",
      },
    ],
    isAction: true,
    isActive: true,
    delay: "1000",
    isButtonFinish: true,
    showContentType: "show-info",
  },
  // #endregion
]

const mobile = [
  // #region แนะนำหน้าหลก
  {
    index: 1,
    tutorialBarPosition: "bottom",
    tutorialBackgroundHeight: "152px",
    tutorialContent: `สวัสดี! ฉันชื่อ <span>วินนี่</span> <br/> จะมาแนะนำการใช้งานใน <span>หน้าหลัก</span> นี้ให้ทุกคนเอง`,
    textAlign: "start",
    isButtonNext: true,
    isButtonBack: false,
    imageBackground: "box-tutorial.webp",
    isBackground: true,
    positionCharacter: "top-right",
    isButtonSkip: true,
    positionButtonSkip: "right",
    infomationContentList: [],
    isAction: true,
    isActive: false,
    delay: "1000",
    delayMobile: "0",
    isButtonFinish: false,
    showContentType: "",
    skipTo: "level-mode",
  },
  {
    index: 2,
    tutorialBarPosition: "bottom",
    tutorialBackgroundHeight: "152px",
    tutorialContent: `เริ่มกันที่ <span>หน้าโปรไฟล์</span> <br/> สามารถแก้ไขข้อมูล, ตรวจสอบคะแนน และ ความก้าวหน้า`,
    textAlign: "start",
    isButtonNext: true,
    isButtonBack: true,
    imageBackground: "box-tutorial.webp",
    isBackground: true,
    positionCharacter: "top-right",
    isButtonSkip: true,
    positionButtonSkip: "right",
    infomationContentList: [
      {
        isShowContent: true,
        content: "ส่วนโปรไฟล์ เลเวลตัวละครและชื่อเล่น",
        position: "top: 118px; left: 50px;",
        isShowHand: true,
        handImage: "/images/icon_main/icon-tutorial-hand.webp",
        handPosition: "top: 52.2px; left: 245px;transform: rotate(90deg);",
      },
    ],

    isAction: true,
    isActive: false,
    delay: "0",
    delayMobile: "0",
    isButtonFinish: false,
    showContentType: "show-profile",
    skipTo: "level-mode",
  },
  {
    index: 3,
    tutorialBarPosition: "bottom",
    tutorialBackgroundHeight: "152px",
    tutorialContent: `เมื่อเข้าที่ หน้าโปรไฟล์ - สถิติแบบฝึกหัด หากมี <span>ความก้าวหน้าเฉลี่ยถึง 80%</span> ก็จะสามารถดาวน์โหลด <span>ใบประกาศ ได้เลย!</span> สู้ๆ นะ!`,
    textAlign: "start",
    isButtonNext: true,
    isButtonBack: true,
    imageBackground: "box-tutorial.webp",
    isBackground: true,
    positionCharacter: "top-right",
    isButtonSkip: true,
    positionButtonSkip: "right",
    infomationContentList: [
      {
        isShowContent: true,
        content: "สถิติแบบฝึกหัดของตัวละคร",
        position: "top: -15px; left: -5px;",
        isShowHand: true,
        handImage: "/images/icon_main/icon-tutorial-hand.webp",
        handPosition: "top: 10px; left: 110px;transform: translateX(-50%) rotateY(180deg) rotate(-17deg);",
      },
      {
        isShowContent: true,
        content: "ห้องใบประกาศ",
        position: "top: 85px; left: 206px;",
        isShowHand: true,
        handImage: "/images/icon_main/icon-tutorial-hand.webp",
        handPosition: "top:68px; left: 157px;transform: rotate(-0deg);",
      },
    ],
    isAction: true,
    isActive: true,
    delay: "0",
    isButtonFinish: false,
    showContentType: "show-profile-detail",
    skipTo: "level-mode",
  },
  {
    index: 4,
    tutorialBarPosition: "bottom",
    tutorialBackgroundHeight: "152px",
    tutorialContent: `ต่อกันที่ มุมขวาบน คือ <span>เมนู</span> ที่รวมรวม การจัดการและเมนูต่างๆ เอาไว้`,
    textAlign: "start",
    isButtonNext: true,
    isButtonBack: true,
    imageBackground: "box-tutorial.webp",
    isBackground: true,
    imageCharacterIdle: "/images/box_main/box-tutorial-professor-winny-1.webp",
    positionCharacter: "top-right",
    isButtonSkip: true,
    positionButtonSkip: "left",
    infomationContentList: [],
    isAction: true,
    isActive: true,
    delay: "0",
    isButtonFinish: false,
    showContentType: "show-button-menu",
    skipTo: "level-mode",
  },
  {
    index: 5,
    tutorialBarPosition: "bottom",
    tutorialBackgroundHeight: "152px",
    tutorialContent: `ได้แก่ <span>กล่องจดหมาย</span>, <span>ตั้งค่า</span> และ <span>ออกจากระบบ</span>`,
    textAlign: "start",
    isButtonNext: true,
    isButtonBack: true,
    imageBackground: "box-tutorial.webp",
    isBackground: true,
    imageCharacterIdle: "/images/box_main/box-tutorial-professor-winny-1.webp",
    positionCharacter: "top-right",
    isButtonSkip: true,
    positionButtonSkip: "left",
    infomationContentList: [
      {
        isShowContent: true,
        content: "กล่องจดหมายและข่าวสาร",
        position: "top: 207px; right: 345px;",
        isShowHand: true,
        handImage: "/images/icon_main/icon-tutorial-hand.webp",
        handPosition: "top: 145px; right: 165px;transform: rotateY(180deg) rotate(70deg);",
      },
      {
        isShowContent: true,
        content: "ตั้งค่าการเล่น",
        position: "top: 245px; right: 135px;",
        isShowHand: true,
        handImage: "/images/icon_main/icon-tutorial-hand.webp",
        handPosition: "top: 182px; right: 55px;transform: rotate(90deg);",
      },
      {
        isShowContent: true,
        content: "ออกจากระบบ",
        position: "top: 51px; right: 175px;",
        isShowHand: true,
        handImage: "/images/icon_main/icon-tutorial-hand.webp",
        handPosition: "top: 78px; right: 47px;transform: rotate(-90deg);",
      },
    ],
    isAction: true,
    isActive: true,
    delay: "0",
    isButtonFinish: false,
    showContentType: "show-button-detail-header",
    skipTo: "level-mode",
  },
  {
    index: 6,
    tutorialBarPosition: "bottom",
    tutorialBackgroundHeight: "152px",
    tutorialContent: `และยังประกอบไปด้วย <span>เมนูต่าง ๆ</span> มากมาย ไว้ลองเข้าไปเล่นกันดูนะ!`,
    textAlign: "start",
    isButtonNext: true,
    isButtonBack: true,
    imageBackground: "box-tutorial.webp",
    isBackground: true,
    imageCharacterIdle: "/images/box_main/box-tutorial-professor-winny-1.webp",
    positionCharacter: "top-right",
    isButtonSkip: true,
    positionButtonSkip: "left",
    infomationContentList: [
      {
        isShowContent: true,
        content: "ลำดับคะแนน",
        position: "top: 120px; right: 310px;",
        isShowHand: true,
        handImage: "/images/icon_main/icon-tutorial-hand.webp",
        handPosition: "top: 150px; right: 215px;transform: rotate(-90deg);",
      },
      {
        isShowContent: true,
        content: "หน้าเก็บอุปกรณ์ <br/> และเสื้อผ้าที่ซื้อมา",
        position: "top: 108px; right: 180px;",
        isShowHand: true,
        handImage: "/images/icon_main/icon-tutorial-hand.webp",
        handPosition: "top: 150px; right: 120px;transform: rotate(-70deg);",
      },
      {
        isShowContent: true,
        content: "กล่องสุ่มปริศนา",
        position: "top: 400px; right: 305px;",
        isShowHand: true,
        handImage: "/images/icon_main/icon-tutorial-hand.webp",
        handPosition: "top: 265px; right: 35px;transform: rotate(100deg);",
      },
      {
        isShowContent: true,
        content: "ร้านค้า",
        position: "top: 330px; right: 100px;",
        isShowHand: true,
        handImage: "/images/icon_main/icon-tutorial-hand.webp",
        handPosition: "top: 340px; right: 200px;transform: rotateY(180deg) rotate(110deg);",
      },
    ],
    isAction: true,
    isActive: true,
    delay: "0",
    isButtonFinish: false,
    showContentType: "show-button-detail-body",
    skipTo: "level-mode",
  },
  {
    index:7,
    tutorialBarPosition: "bottom",
    tutorialBackgroundHeight: "152px",
    tutorialContent: `ปิดท้ายกันที่ มุมขวาล่าง คือ พื้นที่การเรียนรู้ และ<span>กิจกรรมต่าง ๆ</span> เข้าสู่ <span>บทเรียน</span> สุดสนุกได้ที่นี่!`,
    textAlign: "start",
    isButtonNext: true,
    isButtonBack: true,
    imageBackground: "box-tutorial.webp",
    isBackground: true,
    imageCharacterIdle: "/images/box_main/box-tutorial-professor-winny-1.webp",
    positionCharacter: "top-right",
    isButtonSkip: true,
    positionButtonSkip: "left",
    infomationContentList: [
      {
        isShowContent: true,
        content: "กิจกรรม <br/> ทบทวนความรู้",
        position: "bottom:188px; left: -2px;",
        isShowHand: true,
        handImage: "/images/icon_main/icon-tutorial-hand.webp",
        handPosition: "bottom: 110px; left: 30px;transform: rotateY(0deg) rotate(-70deg);",
      },
      {
        isShowContent: true,
        content: "เริ่มเรียน",
        position: "bottom: 225px; left: 125px;",
        isShowHand: true,
        handImage: "/images/icon_main/icon-tutorial-hand.webp",
        handPosition: "bottom: 160px; left:140px;transform: rotateY(180deg) rotate(-80deg);",
      },
      {
        isShowContent: true,
        content: "กิจกรรมพิเศษ",
        position: "bottom: 180px; right: 135px;",
        isShowHand: true,
        handImage: "/images/icon_main/icon-tutorial-hand.webp",
        handPosition: "bottom: 115px; right:45px;transform: rotateY(180deg) rotate(-80deg);",
      },
    ],
    isAction: true,
    isActive: true,
    delay: "0",
    isButtonFinish: false,
    showContentType: "box-button-footer",
    skipTo: "level-mode",
  },
  // #endregion

  // #region ระบบเลเวล
  {
    index: 8,
    tutorialBarPosition: "bottom",
    tutorialBackgroundHeight: "180px",
    tutorialContent: `นี่คือ <span>ระบบเลเวล</span> ตัวเลขที่อยู่บน <span>ตราประดับ</span> เรียกว่า <span>เลเวล</span> ซึ่งตราประดับจะเปลี่ยนแปลงตามเลเวลที่เพิ่มขึ้นของคุณ! เมื่อ<span>เข้าเรียนและทำแบบฝึกหัด</span>คุณก็จะได้รับ <span>ค่า XP</span> เพื่อให้เลเวลอัพ!"`,
    textAlign: "start",
    isButtonNext: true,
    isButtonBack: false,
    imageBackground: "box-tutorial.webp",
    isBackground: true,
    imageCharacterIdle: "/images/box_main/box-tutorial-professor-winny-1.webp",
    positionCharacter: "top-right",
    isButtonSkip: false,
    positionButtonSkip: "left",
    infomationContentList: [
      {
        isShowContent: true,
        content: "เลเวลและตราประดับ",
        position: "top:40px; left: 125px;",
        isShowHand: true,
        handImage: "/images/icon_main/icon-tutorial-hand.webp",
        handPosition: "top: 20px; left: 75px;transform: rotate(15deg);",
      },
    ],
    isAction: true,
    isActive: true,
    delay: "0",
    isButtonFinish: false,
    showContentType: "show-level",
    skipTo: "",
  },
  {
    index: 9,
    tutorialBarPosition: "bottom",
    tutorialBackgroundHeight: "152px",
    tutorialContent: `รู้หรือไม่? ทุกครั้งที่คุณ <span>เลเวลอัพ</span> คุณจะได้รับของ <span>รางวัลสุดพิเศษ!</span> ลองมาดูกันเลยว่าคุณจะได้อะไรบ้างเมื่อเลเวลอัพ!`,
    textAlign: "start",
    isButtonNext: true,
    isButtonBack: true,
    imageBackground: "box-tutorial.webp",
    isBackground: true,
    imageCharacterIdle: "/images/box_main/box-tutorial-professor-winny-1.webp",
    positionCharacter: "top-right",
    isButtonSkip: false,
    positionButtonSkip: "left",
    infomationContentList: [
      {
        isShowContent: true,
        content: "รับรางวัลเมื่อเลเวลอัพ",
        position: "top:175px; left: 35px;",
        isShowHand: true,
        handImage: "/images/icon_main/icon-tutorial-hand.webp",
        handPosition: "top: 110px; left: 75px;transform: rotateY(180deg) rotate(90deg);",
      },
    ],
    isAction: true,
    isActive: true,
    delay: "0",
    isButtonFinish: false,
    showContentType: "show-profile-level-reward",
    skipTo: "",
  },
  {
    index: 10,
    tutorialBarPosition: "bottom",
    tutorialBackgroundHeight: "0px",
    tutorialContent: ``,
    textAlign: "start",
    isButtonNext: false,
    isButtonBack: false,
    imageBackground: "box-tutorial.webp",
    isBackground: false,
    imageCharacterIdle: "/images/box_main/box-tutorial-professor-winny-1.webp",
    positionCharacter: "top-right",
    isButtonSkip: false,
    positionButtonSkip: "left",
    infomationContentList: [
    ],
    isAction: true,
    isActive: true,
    delay: "0",
    isButtonFinish: false,
    showContentType: "show-level-up",
    skipTo: "",
  },
  {
    index: 11,
    tutorialBarPosition: "bottom",
    tutorialBackgroundHeight: "152px",
    tutorialContent: `เลเวลอัพแล้ว <span>กดรับรางวัล (Claim Reward)</span> ดูสิ`,
    textAlign: "center",
    isButtonNext: false,
    isButtonBack: false,
    imageBackground: "box-tutorial.webp",
    isBackground: true,
    imageCharacterIdle: "/images/box_main/box-tutorial-professor-winny-3.webp",
    positionCharacter: "top-right",
    isButtonSkip: false,
    positionButtonSkip: "left",
    infomationContentList: [
      {
        isShowContent: false,
        content: "",
        position: "top: 0%; left:0%;",
        isShowHand: true,
        handImage: "/images/icon_main/icon-tutorial-hand.webp",
        handPosition: "bottom: -3px; left: 30px;transform: rotateY(180deg) rotate(70deg);",
        isAnimtionHand: true,
      },
    ],
    isAction: true,
    isActive: true,
    delay: "0",
    isButtonFinish: false,
    showContentType: "show-level-up-success",
    skipTo: "",
  },
  {
    index: 12,
    tutorialBarPosition: "top",
    tutorialBackgroundHeight: "120px",
    tutorialContent: `กด <span>รับทั้งหมด (Claim All)</span> เพื่อรับรางวัลทั้งหมดได้เลย!`,
    textAlign: "center",
    isButtonNext: false,
    isButtonBack: false,
    imageBackground: "box-tutorial.webp",
    isBackground: true,
    imageCharacterIdle: "/images/box_main/box-tutorial-professor-winny-1.webp",
    positionCharacter: "bottom-right",
    isButtonSkip: false,
    positionButtonSkip: "left",
    infomationContentList: [
      {
        isShowContent: false,
        content: "",
        position: "top: 0%; left:0%;",
        isShowHand: true,
        handImage: "/images/icon_main/icon-tutorial-hand.webp",
        handPosition: "bottom:0px; left: 75%;transform: rotate(70deg);",
        isAnimtionHand: true,
      },
    ],
    isAction: true,
    isActive: true,
    delay: "0",
    isButtonFinish: false,
    showContentType: "show-dialog-level-reward",
    skipTo: "",
  },
  {
    index: 13,
    tutorialBarPosition: "bottom",
    tutorialBackgroundHeight: "0px",
    tutorialContent: ``,
    isButtonNext: false,
    isButtonBack: false,
    imageBackground: "box-tutorial.webp",
    isBackground: false,
    imageCharacterIdle: "/images/box_main/box-tutorial-professor-winny-3.webp",
    positionCharacter: "right",
    isButtonSkip: false,
    positionButtonSkip: "left",
    infomationContentList: [],
    isAction: true,
    isActive: true,
    delay: "0",
    isButtonFinish: false,
    showContentType: "show-get-reward",
    skipTo: "",
  },
  // #endregion

  // #region โหมดการเรียนเป็นคู่
  {
    index: 14,
    tutorialBarPosition: "bottom",
    tutorialBackgroundHeight: "170px",
    tutorialContent: `นอกจากนี้ การเข้าสู่ <span>โหมดการเรียนเป็นคู่ (Buddy Mode)</span> ให้นักเรียนกรอก <span>รหัสผู้ใช้งาน และรหัสผ่าน</span> ของเพื่อนที่ต้องการจับคู่ จากนั้นกดปุ่ม <span>เริ่มจับคู่ (Pair)</span>`,
    textAlign: "start",
    isButtonNext: true,
    isButtonBack: false,
    imageBackground: "box-tutorial.webp",
    isBackground: true,
    imageCharacterIdle: "/images/box_main/box-tutorial-professor-winny-1.webp",
    positionCharacter: "top-right",
    isButtonSkip: true,
    positionButtonSkip: "right",
    infomationContentList: [
      {
        isShowContent: true,
        content: "โหมดการเรียนเป็นคู่",
        position: "top: 61px; left:172px;",
        isShowHand: true,
        handImage: "/images/icon_main/icon-tutorial-hand.webp",
        handPosition: "top:50px; left:125px;transform:rotate(0deg);",
      },
    ],
    isAction: true,
    isActive: true,
    delay: "0",
    isButtonFinish: false,
    showContentType: "show-buddy-mode",
    skipTo: "finish-mode",
  },
  {
    index: 15,
    tutorialBarPosition: "bottom",
    tutorialBackgroundHeight: "152px",
    tutorialContent: `และเมื่อต้องการ <span>ออกจากโหมดการเรียนเป็นคู่</span> ให้กด <span>เลิกจับคู่ (Unpair)</span> เพื่อออกจากการจับคู่`,
    textAlign: "start",
    isButtonNext: true,
    isButtonBack: true,
    imageBackground: "box-tutorial.webp",
    isBackground: true,
    imageCharacterIdle: "/images/box_main/box-tutorial-professor-winny-1.webp",
    positionCharacter: "top-right",
    isButtonSkip: true,
    positionButtonSkip: "right",
    infomationContentList: [
      {
        isShowContent: true,
        content: "ออกจากโหมดจับคู่",
        position: "top: 210px; left:195px;",
        isShowHand: true,
        handImage: "/images/icon_main/icon-tutorial-hand.webp",
        handPosition: "top:147px; left:240px;transform:rotate(70deg);",
      },
    ],
    isAction: true,
    isActive: true,
    delay: "0",
    isButtonFinish: false,
    showContentType: "show-unpair-buddy-mode",
    skipTo: "finish-mode",
  },
  // #endregion

  // #region จบการสอน
  {
    index: 16,
    tutorialBarPosition: "bottom",
    tutorialBackgroundHeight: "152px",

    tutorialContent: `พร้อมสำหรับการเรียน
กันแล้ว! ถ้าสงสัยตรงไหน <span>กดปุ่ม</span> <span
            style="
              padding: clamp(1.875px, 0.1875vw, 3px) clamp(6.25px, 0.625vw, 10px);
              border: clamp(1.875px, 0.1875vw, 3px) solid #f7b90d;
              border-radius: 50%;
              font-size: clamp(12px, 1.2vw, 20px);
              color:#f7b90d;
            "
            class="fas fa-info"
          ></span> <span>เพื่อดูคำแนะนำอีกครั้งได้นะ</span> <br/>
ขอให้สนุกในการเรียนไปกับ Winner English`,
    textAlign: "start",
    isButtonNext: true,
    isButtonBack: false,
    imageBackground: "box-tutorial.webp",
    isBackground: true,
    imageCharacterIdle: "/images/box_main/box-tutorial-professor-winny-3.webp",
    imageCharacterAction: "/images/box_main/box-tutorial-professor-winny-2.webp",
    positionCharacter: "top-right",
    isButtonSkip: false,
    positionButtonSkip: "right",
    infomationContentList: [
      {
        isShowContent: true,
        content: "แนะนำการใช้งาน",
        position: "top: 85px; left:93px;",
        isShowHand: true,
        handImage: "/images/icon_main/icon-tutorial-hand.webp",
        handPosition: "top:30px; left: 224px;transform: rotate(-60deg) rotateY(180deg);",
      },
    ],
    isAction: true,
    isActive: true,
    delay: "1000",
    isButtonFinish: true,
    showContentType: "show-info",
  },
  // #endregion
]

export default {
  desktop,
  mobile
}
