// Section Tutorial Gacha
// #region Desktop
const tutorialGacha = [
  {
    tutorialBarPosition: "absolute-bottom",
    text: "มาทำความรู้จักกับการสุ่มรับรางวัลสุดพิเศษที่ <span style='color:#F7B90D'>Mystery Box</span> กัน",
    winnyPosition: "absolute-bottom-left",
    isOpenBox: false,
    isShowHeaderBarKey: false,
    isShowHeaderBarCoin: false,
    isShowRateUpLimited: false,
    isShowPremiumBox: false,
    isShowStandardBox: false,
    isShowHandLeft: false,
    isShowHandRight: false,
    positionHandLeft: '',
    positionHandRight: '',
    isDisableButton: true,
    positionButtonNext: "left: 90%;",
    isNextButton: true,
  },
  {
    tutorialBarPosition: "absolute-bottom",
    text: "กล่องสุ่มรางวัลมี 2 กล่อง คือ <span style='color:#F7B90D'>Premium</span> และ <span style='color:#F7B90D'>Standard</span><br/> ของรางวัลข้างในจะมีความแตกต่างกัน",
    winnyPosition: "absolute-bottom-left",
    isOpenBox: false,
    isShowHeaderBarKey: false,
    isShowHeaderBarCoin: false,
    isShowRateUpLimited: false,
    isShowPremiumBox: true,
    isShowStandardBox: true,
    isShowHandLeft: false,
    isShowHandRight: true,
    positionHandLeft: '',
    positionHandRight: 'left:62%;top:5%;',
    isDisableButton: true,
    positionButtonNext: "left: 90%;",
    isNextButton: true,
  },
  {
    tutorialBarPosition: "absolute-bottom",
    text: "โดยกล่อง <span style='color:#F7B90D'>Premium</span> มีรางวัลพิเศษที่จะเปลี่ยนทุก 2 เดือน ซึ่งหาซื้อในช้อปไม่ได้ <br> และชุดตาม <span style='color:#F7B90D'>Season</span>  ที่ผ่านมาแล้วในช้อป สามารถเปิดด้วย <span style='color:#F7B90D'>กุญแจ</span> เท่านั้น",
    winnyPosition: "absolute-bottom-left",
    isOpenBox: false,
    isShowHeaderBarKey: true,
    isShowHeaderBarCoin: false,
    isShowRateUpLimited: false,
    isShowPremiumBox: true,
    isShowStandardBox: false,
    isShowHandLeft: true,
    isShowHandRight: true,
    positionHandLeft: 'top:-1%;left:25.7%;',
    positionHandRight: 'top:9.5%;left:44%;',
    isDisableButton: true,
    positionButtonNext: "left: 90%;",
    isNextButton: true,
  },
  {
    tutorialBarPosition: "absolute-bottom",
    text: "ส่วนกล่อง <span style='color:#F7B90D'>Standard</span> จะเป็นรางวัลที่ซื้อได้ตามช้อป <br/> และยังสามารถได้รับ<span style='color:#F7B90D'>กุญแจ</span>สำหรับเปิดกล่อง <span style='color:#F7B90D'>Premium</span>",
    winnyPosition: "absolute-bottom-left",
    isOpenBox: false,
    isShowHeaderBarKey: false,
    isShowHeaderBarCoin: true,
    isShowRateUpLimited: false,
    isShowPremiumBox: false,
    isShowStandardBox: true,
    isShowHandLeft: true,
    isShowHandRight: true,
    positionHandLeft: 'top:-1.5%;left:16.7%;',
    positionHandRight: 'top:9.7%;left:66.5%;',
    isDisableButton: true,
    positionButtonNext: "left: 90%;",
    isNextButton: true,
  },
  {
    tutorialBarPosition: "absolute-top",
    text: "เรามาลองเปิดกล่อง <span style='color:#F7B90D'>Mystery Box</span> ระดับ <span style='color:#F7B90D'>Standard</span> กันเถอะ<br/> ในครั้งแรก เราไม่เก็บเหรียญนะกดได้เลย",
    winnyPosition: "absolute-top-left",
    isOpenBox: true,
    isShowHeaderBarKey: false,
    isShowHeaderBarCoin: false,
    isShowRateUpLimited: false,
    isShowPremiumBox: false,
    isShowStandardBox: true,
    isShowHandLeft: false,
    isShowHandRight: true,
    positionHandLeft: '',
    positionHandRight: 'top:65%;left:67%;',
    isDisableButton: false,
    positionButtonNext: "left: 90%;",
    isNextButton: false,
  },
  {
    tutorialBarPosition: "absolute-top",
    text: "ได้รับกุญแจแล้วลองมาเปิดกล่อง <span style='color:#F7B90D'>Mystery Box</span> ระดับ <span style='color:#F7B90D'>Premium</span><br/> มาลุ้นกันจะได้รางวัลอะไร",
    winnyPosition: "absolute-top-left",
    isOpenBox: true,
    isShowHeaderBarKey: false,
    isShowHeaderBarCoin: false,
    isShowRateUpLimited: false,
    isShowPremiumBox: true,
    isShowStandardBox: false,
    isShowHandLeft: false,
    isShowHandRight: true,
    positionHandLeft: '',
    positionHandRight: 'top:65%;left:44%;',
    positionButtonNext: "",
    isDisableButton: true,
    positionButtonNext: "left: 90%;",
    isNextButton: false,
  },
  {
    tutorialBarPosition: "absolute-top",
    text: "ถ้าในกรณีที่ได้รับชุด <span style='color:#F7B90D'>Limited</span> ซ้ำ จะเป็นการสะสมคะแนน<br/> เมื่อ<span style='color:#F7B90D'>ครบ 10 คะแนน</span> ก็สามารถรับชุด <span style='color:#F7B90D'>Limited</span> ได้เหมือนกัน",
    winnyPosition: "absolute-top-right",
    isOpenBox: false,
    isShowHeaderBarKey: false,
    isShowHeaderBarCoin: false,
    isShowRateUpLimited: true,
    isShowPremiumBox: false,
    isShowStandardBox: false,
    isShowHandLeft: true,
    isShowHandRight: false,
    positionHandLeft: 'top:17%;left:50%;transform: rotate(-35deg);transform-origin:bottom;',
    positionHandRight: '',
    isDisableButton: true,
    positionButtonNext: "left: 75%;",
    isNextButton: true,
  },
  {
    tutorialBarPosition: "absolute-top",
    text: "เป็นยังไงกันบ้างกับการสุ่มของรางวัลที่พี่วินนี่นำมาให้เล่นกัน<br/> ไปสะสมเหรียญ เพื่อสุ่มรางวัลกันนะ",
    winnyPosition: "absolute-center",
    isOpenBox: false,
    isShowHeaderBarKey: false,
    isShowHeaderBarCoin: false,
    isShowRateUpLimited: false,
    isShowPremiumBox: false,
    isShowStandardBox: false,
    isShowHandLeft: false,
    isShowHandRight: false,
    positionHandLeft: '',
    positionHandRight: '',
    isDisableButton: true,
    positionButtonNext: "top:55%;left: 80%;",
    isNextButton: true,
  }
]
// #endregion

// #region Mobile
const tutorialGachaMobile = [
  {
    tutorialBarPosition: "absolute-bottom",
    text: "มาทำความรู้จักกับการสุ่มรับรางวัลสุดพิเศษที่ <span style='color:#F7B90D'>Mystery Box</span> กัน",
    winnyPosition: "absolute-bottom-left",
    isOpenBox: false,
    isShowHeaderBarKey: false,
    isShowHeaderBarCoin: false,
    isShowRateUpLimited: false,
    isShowPremiumBox: false,
    isShowPremiumButton: false,
    isShowStandardBox: false,
    isShowStandardButton:false,
    isShowHandLeft: false,
    isShowHandRight: false,
    positionHandLeft: '',
    positionHandRight: '',
    isDisableButton: true,
    positionButtonNext: "",
    isNextButton: true,
  },
  {
    tutorialBarPosition: "absolute-bottom",
    text: "กล่อง <span style='color:#F7B90D'>Premium</span> มีรางวัลพิเศษ <br/> จะเปลี่ยนทุก 2 เดือน หาซื้อในช้อปไม่ได้ และชุดตาม <span style='color:#F7B90D'>Season</span> ที่ผ่านมาแล้วในช้อปเปิดด้วย<span style='color:#F7B90D'>กุญแจ</span>เท่านั้น",
    winnyPosition: "absolute-bottom-left",
    isOpenBox: false,
    isShowHeaderBarKey: true,
    isShowHeaderBarCoin: false,
    isShowRateUpLimited: false,
    isShowPremiumBox: true,
    isShowPremiumButton: false,
    isShowStandardBox: false,
    isShowStandardButton:false,
    isShowHandLeft: false,
    isShowHandRight: true,
    positionHandLeft: '',
    positionHandRight: '',
    isDisableButton: true,
    positionButtonNext: "",
    isNextButton: true,
  },
  {
    tutorialBarPosition: "absolute-bottom",
    text: "ส่วนกล่อง <span style='color:#F7B90D'>Standard</span> <br/> จะเป็นรางวัลที่ซื้อได้ตามช้อป และยังสามารถได้รับกุญแจสำหรับเปิดกล่อง <span style='color:#F7B90D'>Premium</span>",
    winnyPosition: "absolute-bottom-left",
    isOpenBox: false,
    isShowHeaderBarKey: false,
    isShowHeaderBarCoin: true,
    isShowRateUpLimited: false,
    isShowPremiumBox: false,
    isShowPremiumButton: false,
    isShowStandardBox: true,
    isShowStandardButton:false,
    isShowHandLeft: true,
    isShowHandRight: false,
    positionHandLeft: '',
    positionHandRight: '',
    isDisableButton: true,
    positionButtonNext: "",
    isNextButton: true,
  },
  {
    tutorialBarPosition: "absolute-top",
    text: "เรามาลองเปิดกล่อง <span style='color:#F7B90D'>Mystery Box</span> ระดับ <span style='color:#F7B90D'>Standard<span></span> กันเถอะ ในครั้งแรก เราไม่เก็บเหรียญนะ กดเลย",
    winnyPosition: "absolute-bottom-left",
    isOpenBox: true,
    isShowHeaderBarKey: false,
    isShowHeaderBarCoin: false,
    isShowRateUpLimited: false,
    isShowPremiumBox: false,
    isShowPremiumButton: false,
    isShowStandardBox: false,
    isShowStandardButton:true,
    isShowHandLeft: true,
    isShowHandRight: false,
    positionHandLeft: '',
    positionHandRight: '',
    isDisableButton: true,
    positionButtonNext: "",
    isNextButton: false,
  },
  {
    tutorialBarPosition: "absolute-top",
    text: "ได้กุญแจแล้วลองมาเปิดกล่อง <span style='color:#F7B90D'>Mystery Box</span> ระดับ <span style='color:#F7B90D'>Premium</span> มาลุ้นกันจะได้รางวัลอะไร",
    winnyPosition: "absolute-bottom-left",
    isOpenBox: true,
    isShowHeaderBarKey: false,
    isShowHeaderBarCoin: false,
    isShowRateUpLimited: false,
    isShowPremiumBox: false,
    isShowPremiumButton: true,
    isShowStandardBox: false,
    isShowStandardButton:false,
    isShowHandLeft: true,
    isShowHandRight: false,
    positionHandLeft: '',
    positionHandRight: '',
    isDisableButton: true,
    positionButtonNext: "",
    isNextButton: false,
  },
  {
    tutorialBarPosition: "absolute-top",
    text: "ถ้าในกรณีที่ได้ชุด <span style='color:#F7B90D'>Limited</span> ซ้ำ จะเป็นการสะสมคะแนน เมื่อ<span style='color:#F7B90D'>ครบ 10 คะแนน</span> ก็สามารถรับชุด <span style='color:#F7B90D'>Limited</span> ได้เหมือนกัน",
    winnyPosition: "absolute-bottom-left",
    isOpenBox: false,
    isShowHeaderBarKey: false,
    isShowHeaderBarCoin: false,
    isShowRateUpLimited: true,
    isShowPremiumBox: false,
    isShowPremiumButton: false,
    isShowStandardBox: false,
    isShowStandardButton:false,
    isShowHandLeft: true,
    isShowHandRight: false,
    positionHandLeft: '',
    positionHandRight: '',
    isDisableButton: true,
    positionButtonNext: "",
    isNextButton: true,
  },
  {
    tutorialBarPosition: "absolute-top",
    text: "เป็นยังไงกันบ้างกับการสุ่มของรางวัลที่พี่วินนี่นำมาให้เล่นกัน ไปสะสมเหรียญ เพื่อสุ่มรางวัลกันนะ",
    winnyPosition: "absolute-center",
    isOpenBox: false,
    isShowHeaderBarKey: false,
    isShowHeaderBarCoin: false,
    isShowRateUpLimited: false,
    isShowPremiumBox: false,
    isShowPremiumButton: false,
    isShowStandardBox: false,
    isShowStandardButton:false,
    isShowHandLeft: false,
    isShowHandRight: false,
    positionHandLeft: '',
    positionHandRight: '',
    isDisableButton: true,
    positionButtonNext: "",
    isNextButton: true,
  }
]
// #endregion

export default { tutorialGacha, tutorialGachaMobile }
